name: 🐞 Bug Report
description: Report a bug encountered while using the MetisFL framework
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report 🤗
  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the [existing issues](https://github.com/MetisFL-AI/metisfl/issues) and there is no existing issue for this bug.
        required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: |
        Please provide a clear description of what the bug is.

        If relevant, add a minimal example so that we can reproduce the error by running the code. For example 

        If the code is too long, feel free to put it in a public gist and link it here: https://gist.github.com.

        Please also paste or describe the results you observe instead of the expected results. If you observe an error, please paste the error message including the **full** traceback of the exception. It may be relevant to wrap error messages in ```` ```triple quotes blocks``` ````.
      placeholder: |
        A clear and concise description of what the bug is.

        ```python
        Sample code to reproduce the problem
        ```

        ```
        The error message you got, with the full traceback.
    validations:
      required: true
  - type: markdown
    attributes:
      value: >
        Thanks for contributing 🎉!
