# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metisfl/proto/service_common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"metisfl/proto/service_common.proto\x12\x07metisfl\x1a\x1fgoogle/protobuf/timestamp.proto\"U\n\x03\x41\x63k\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07message\x18\x03 \x01(\t\" \n\x1eGetServicesHealthStatusRequest\"\xaf\x01\n\x1fGetServicesHealthStatusResponse\x12U\n\x0fservices_status\x18\x01 \x03(\x0b\x32<.metisfl.GetServicesHealthStatusResponse.ServicesStatusEntry\x1a\x35\n\x13ServicesStatusEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\"\x11\n\x0fShutDownRequest\"-\n\x10ShutDownResponse\x12\x19\n\x03\x61\x63k\x18\x01 \x01(\x0b\x32\x0c.metisfl.Ackb\x06proto3')



_ACK = DESCRIPTOR.message_types_by_name['Ack']
_GETSERVICESHEALTHSTATUSREQUEST = DESCRIPTOR.message_types_by_name['GetServicesHealthStatusRequest']
_GETSERVICESHEALTHSTATUSRESPONSE = DESCRIPTOR.message_types_by_name['GetServicesHealthStatusResponse']
_GETSERVICESHEALTHSTATUSRESPONSE_SERVICESSTATUSENTRY = _GETSERVICESHEALTHSTATUSRESPONSE.nested_types_by_name['ServicesStatusEntry']
_SHUTDOWNREQUEST = DESCRIPTOR.message_types_by_name['ShutDownRequest']
_SHUTDOWNRESPONSE = DESCRIPTOR.message_types_by_name['ShutDownResponse']
Ack = _reflection.GeneratedProtocolMessageType('Ack', (_message.Message,), {
  'DESCRIPTOR' : _ACK,
  '__module__' : 'metisfl.proto.service_common_pb2'
  # @@protoc_insertion_point(class_scope:metisfl.Ack)
  })
_sym_db.RegisterMessage(Ack)

GetServicesHealthStatusRequest = _reflection.GeneratedProtocolMessageType('GetServicesHealthStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSERVICESHEALTHSTATUSREQUEST,
  '__module__' : 'metisfl.proto.service_common_pb2'
  # @@protoc_insertion_point(class_scope:metisfl.GetServicesHealthStatusRequest)
  })
_sym_db.RegisterMessage(GetServicesHealthStatusRequest)

GetServicesHealthStatusResponse = _reflection.GeneratedProtocolMessageType('GetServicesHealthStatusResponse', (_message.Message,), {

  'ServicesStatusEntry' : _reflection.GeneratedProtocolMessageType('ServicesStatusEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETSERVICESHEALTHSTATUSRESPONSE_SERVICESSTATUSENTRY,
    '__module__' : 'metisfl.proto.service_common_pb2'
    # @@protoc_insertion_point(class_scope:metisfl.GetServicesHealthStatusResponse.ServicesStatusEntry)
    })
  ,
  'DESCRIPTOR' : _GETSERVICESHEALTHSTATUSRESPONSE,
  '__module__' : 'metisfl.proto.service_common_pb2'
  # @@protoc_insertion_point(class_scope:metisfl.GetServicesHealthStatusResponse)
  })
_sym_db.RegisterMessage(GetServicesHealthStatusResponse)
_sym_db.RegisterMessage(GetServicesHealthStatusResponse.ServicesStatusEntry)

ShutDownRequest = _reflection.GeneratedProtocolMessageType('ShutDownRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHUTDOWNREQUEST,
  '__module__' : 'metisfl.proto.service_common_pb2'
  # @@protoc_insertion_point(class_scope:metisfl.ShutDownRequest)
  })
_sym_db.RegisterMessage(ShutDownRequest)

ShutDownResponse = _reflection.GeneratedProtocolMessageType('ShutDownResponse', (_message.Message,), {
  'DESCRIPTOR' : _SHUTDOWNRESPONSE,
  '__module__' : 'metisfl.proto.service_common_pb2'
  # @@protoc_insertion_point(class_scope:metisfl.ShutDownResponse)
  })
_sym_db.RegisterMessage(ShutDownResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETSERVICESHEALTHSTATUSRESPONSE_SERVICESSTATUSENTRY._options = None
  _GETSERVICESHEALTHSTATUSRESPONSE_SERVICESSTATUSENTRY._serialized_options = b'8\001'
  _ACK._serialized_start=80
  _ACK._serialized_end=165
  _GETSERVICESHEALTHSTATUSREQUEST._serialized_start=167
  _GETSERVICESHEALTHSTATUSREQUEST._serialized_end=199
  _GETSERVICESHEALTHSTATUSRESPONSE._serialized_start=202
  _GETSERVICESHEALTHSTATUSRESPONSE._serialized_end=377
  _GETSERVICESHEALTHSTATUSRESPONSE_SERVICESSTATUSENTRY._serialized_start=324
  _GETSERVICESHEALTHSTATUSRESPONSE_SERVICESSTATUSENTRY._serialized_end=377
  _SHUTDOWNREQUEST._serialized_start=379
  _SHUTDOWNREQUEST._serialized_end=396
  _SHUTDOWNRESPONSE._serialized_start=398
  _SHUTDOWNRESPONSE._serialized_end=443
# @@protoc_insertion_point(module_scope)
